export const Routes = {
    HOME: '/',
    LOGIN: '/auth/login',
    SIGNUP: '/auth/signup',
    LOGIN_CALLBACK: '/login-callback',
    WEBTOON_NEW: '/webtoon/new',
    WEBTOON_ONGOING: '/webtoon/ongoing',
    WEBTOON_COMPLETED: '/webtoon/completed',
    WEBTOON_DETAIL: (id: string) => `/webtoon/${id}`,
    WEBTOON_RATING_LIST: '/webtoon/rating-list',
    USER_PROFILE: '/user/profile',
    USER_PROFILE_EDIT: '/user/profile/edit',
    NOTIFICATION_SETTINGS: '/user/notification-settings',
    READING_HISTORY: '/user/reading-history',
    MASTERPIECE_WEBTOONS: '/user/masterpiece-webtoons',
    ADULT_VERIFICATION: '/user/adult-verification',
    TUTORIAL: '/tutorial',
    PASSWORD_CHANGE: '/user/password-change',
    BOOKMARKED_WEBTOONS: '/user/bookmarked-webtoons',
    FAVORITE_WEBTOONS: '/user/favorite-webtoons',
    COLLECTIONS: '/user/collections',
    COLLECTION_CREATE: '/user/collections/create',
    COLLECTION_DETAIL: '/user/collections/:collectionId',
    COLLECTION_EDIT: '/user/collections/:collectionId/edit',
    ACHIEVEMENTS: '/user/achievements',
    PREFERENCES: '/user/preferences',
    ERROR: '/error',
    SOCIAL_LOGIN_CALLBACK: '/auth/social-login-callback',
    ONGOING_WEBTOONS: '/webtoon/ongoing',
    WEBTOON_EXPLORE: '/webtoon/explore',
    WEBTOON_DETAILS: '/webtoon/:webtoonId',
    PROFILE: '/user/profile',
    PROFILE_EDIT: '/user/profile/edit',
} as const;